workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      groups:
        - apple-connect   # APP_STORE_CONNECT_ISSUER_ID / KEY_IDENTIFIER / PRIVATE_KEY
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor iOS (recreate if core files missing)
      - |
        echo "👉 Setting up Capacitor"
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/ios --save --no-fund --no-audit || true
        npx cap init "X45 Express Fitness" "com.expressfitness.x45" --web-dir=www || true

        # If ios platform is incomplete, recreate it
        if [ ! -f ios/App/App.xcodeproj ] || [ ! -f ios/App/Podfile ]; then
          echo "🧹 iOS platform incomplete → recreating"
          rm -rf ios
          npx cap add ios
        fi

        # Copy web assets into the native project
        npx cap copy ios

      # 2) Install CocoaPods (creates/updates .xcworkspace)
      - |
        echo "📦 Installing CocoaPods"
        cd ios/App
        pod install --repo-update
        cd ../../

      # 3) FORCE the bundle identifier to match signing (fixes profile mismatch)
      - |
        echo "🪛 Forcing CFBundleIdentifier to com.expressfitness.x45"
        /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.expressfitness.x45" ios/App/App/Info.plist || \
        /usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string com.expressfitness.x45" ios/App/App/Info.plist
        echo "🔎 Info.plist CFBundleIdentifier:"
        /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/App/App/Info.plist

      # 4) Fetch signing files and apply to the Xcode project
      - |
        echo "🔐 Fetching & applying signing profiles"
        keychain initialize
        app-store-connect fetch-signing-files "com.expressfitness.x45" --type IOS_APP_STORE --create
        cd ios/App
        xcode-project use-profiles
        cd ../../

      # 5) Build signed IPA (workspace + export options)
      - |
        echo "🏗️ Building signed IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination 'generic/platform=iOS'" \
          --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
