workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.expressfitness.x45
      groups:
        - apple-connect   # APP_STORE_CONNECT_* + CERTIFICATE_PRIVATE_KEY
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor iOS + create a resilient Podfile first
      - |
        set -euo pipefail
        echo "👉 Setting up Capacitor (idempotent)"
        npm i -g @capacitor/cli
        npm i @capacitor/core @capacitor/ios --save --no-fund --no-audit || true

        if [ ! -d ios ]; then
          echo "➕ Adding iOS platform"
          npx cap add ios
        fi

        # Create a resilient Podfile (handles missing pods_helpers gracefully)
        cat > ios/App/Podfile <<'RUBY'
        helper_path = File.expand_path('../../node_modules/@capacitor/ios/scripts/pods_helpers', __FILE__)
        begin
          require helper_path
        rescue LoadError
          # Fallback: define minimal helpers so pod install succeeds even if helper isn't found
          def capacitor_pods
            pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
            pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
          end
          def assertDeploymentTarget(installer); end
        end

        platform :ios, '13.0'
        use_frameworks! :linkage => :static

        target 'App' do
          capacitor_pods
          # Add Capacitor plugins here as needed, e.g.:
          # pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
          # pod 'CapacitorHaptics',    :path => '../../node_modules/@capacitor/haptics'
        end

        post_install do |installer|
          assertDeploymentTarget(installer) if defined?(assertDeploymentTarget)
        end
        RUBY

        # Sync native assets (don't rely on sync to manage pods)
        npx cap copy ios
        npx cap sync ios || true

      # 2) CocoaPods (creates workspace if missing)
      - |
        set -euo pipefail
        echo "📦 Installing CocoaPods"
        cd ios/App
        pod install --repo-update
        cd ../../
        ls -la ios/App

      # 3) Fetch signing files and apply them to workspace/scheme
      - |
        set -euo pipefail
        echo "🔐 Fetching & applying signing profiles"
        keychain initialize

        app-store-connect fetch-signing-files "$BUNDLE_ID" \
          --type IOS_APP_STORE \
          --create \
          --certificate-private-key "$CERTIFICATE_PRIVATE_KEY"

        keychain add-certificates

        xcode-project use-profiles \
          --workspace ios/App/App.xcworkspace \
          --scheme App

      # 4) Build signed IPA (Release)
      - |
        set -euo pipefail
        echo "🏗️ Archiving & exporting IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination generic/platform=iOS"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log
      - ~/Library/Logs/gym/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
