workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.expressfitness.x45
        APP_NAME: X45
      groups:
        - apple-connect   # APP_STORE_CONNECT_ISSUER_ID / APP_STORE_CONNECT_KEY_IDENTIFIER / APP_STORE_CONNECT_PRIVATE_KEY

    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Clean + recreate Capacitor iOS (iOS 15) and Podfile
      - |
        set -euo pipefail
        npm i -g @capacitor/cli
        npm i @capacitor/core @capacitor/ios --save --no-fund --no-audit || true

        [ -f package.json ] || npm init -y
        mkdir -p www
        [ -f www/index.html ] || echo "<!doctype html><meta charset='utf-8'><title>X45</title><div>X45</div>" > www/index.html

        node -e "const fs=require('fs');fs.writeFileSync('capacitor.config.json',JSON.stringify({appId:'${BUNDLE_ID}',appName:'${APP_NAME}',webDir:'www',bundledWebRuntime:false},null,2))"

        rm -rf ios
        npx cap init "${APP_NAME}" "${BUNDLE_ID}" --web-dir=www --no-interactive || true
        npx cap add ios
        npx cap copy ios
        npx cap sync ios || true

        test -d ios/App/App.xcodeproj || (echo 'Missing ios/App/App.xcodeproj' && exit 1)

        /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" ios/App/App/Info.plist || true

        rm -f ios/App/Podfile
        {
          printf "platform :ios, '15.0'\n"
          printf "use_frameworks! :linkage => :static\n"
          printf "project 'App.xcodeproj'\n\n"
          printf "target 'App' do\n"
          printf "  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'\n"
          printf "  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'\n"
          printf "end\n"
        } >> ios/App/Podfile

      # 2) CocoaPods
      - |
        set -euo pipefail
        cd ios/App
        rm -f Podfile.lock
        rm -rf Pods
        pod repo update
        pod install --repo-update
        cd ../../

      # 3) Fetch signing files, apply to project, bump build, archive, export, upload
      - |
        set -euo pipefail

        keychain initialize
        app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
        keychain add-certificates

        # Apply profiles to the Xcode project (no --scheme flag)
        xcode-project use-profiles --project ios/App/App.xcodeproj

        # Get App Store profile + team
        PROFILE_PATH="$(ls -t /Users/builder/Library/MobileDevice/Provisioning\ Profiles/IOS_APP_STORE_*.mobileprovision | head -n1)"
        [ -f "$PROFILE_PATH" ] || (echo "No IOS_APP_STORE profile found"; ls -la /Users/builder/Library/MobileDevice/Provisioning\ Profiles/; exit 1)
        TMP_PLIST="$(mktemp)"; /usr/bin/security cms -D -i "$PROFILE_PATH" > "$TMP_PLIST"
        PROFILE_NAME="$(/usr/libexec/PlistBuddy -c 'Print :Name' "$TMP_PLIST")"
        TEAM_ID="$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' "$TMP_PLIST")"

        # ===== CHANGE #1: bump build number (CFBundleVersion)
        BUILD_NUM="${BUILD_NUMBER:-${CM_BUILD_ID:-$(date +%Y%m%d%H%M)}}"
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUM}" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NUM}" ios/App/App/Info.plist
        /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" ios/App/App/Info.plist >/dev/null 2>&1 || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.0.0" ios/App/App/Info.plist

        # ===== CHANGE #2: clear export-compliance prompt (HTTPS-only apps)
        /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption NO" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool NO" ios/App/App/Info.plist

        # Archive (workspace because of Pods)
        mkdir -p build/ios
        xcodebuild \
          -workspace ios/App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath build/ios/App.xcarchive \
          -destination "generic/platform=iOS" \
          clean archive \
          CURRENT_PROJECT_VERSION="${BUILD_NUM}"

        # Export using the fetched profile name
        cat > build/ios/ExportOptions.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key><string>app-store</string>
          <key>signingStyle</key><string>manual</string>
          <key>teamID</key><string>${TEAM_ID}</string>
          <key>provisioningProfiles</key>
          <dict>
            <key>${BUNDLE_ID}</key><string>${PROFILE_NAME}</string>
          </dict>
          <key>stripSwiftSymbols</key><true/>
          <key>compileBitcode</key><false/>
          <key>uploadBitcode</key><false/>
        </dict>
        </plist>
        EOF

        xcodebuild -exportArchive \
          -archivePath build/ios/App.xcarchive \
          -exportOptionsPlist build/ios/ExportOptions.plist \
          -exportPath build/ios/ipa

        # ===== CHANGE #3: upload to TestFlight (Internal Testing group)
        IPA_PATH="$(ls -t build/ios/ipa/*.ipa | head -n1)"
        echo "🚀 Uploading to TestFlight: $IPA_PATH"
        app-store-connect publish \
          --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
          --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
          --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
          --path "$IPA_PATH" \
          --testflight \
          --beta-groups "Internal Testing"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/**/*.xcarchive
      - ios/App/build/**/*.log
      - ~/Library/Logs/gym/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
