workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      groups:
        - apple-connect   # uses your APP_STORE_CONNECT_* vars
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor iOS (recreate if core files are missing)
      - |
        echo "👉 Setting up Capacitor"
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/ios --save --no-fund --no-audit || true
        npx cap init "X45 Express Fitness" "com.expressfitness.x45" --web-dir=www || true

        # If ios/App/App.xcodeproj or ios/App/Podfile is missing, recreate the iOS platform
        if [ ! -f ios/App/App.xcodeproj ] || [ ! -f ios/App/Podfile ]; then
          echo "🧹 iOS platform incomplete → recreating"
          rm -rf ios
          npx cap add ios
        fi

        # Copy web assets into the native project
        npx cap copy ios

      # 2) Install CocoaPods (creates/updates .xcworkspace)
      - |
        echo "📦 Installing CocoaPods"
        cd ios/App
        pod install --repo-update
        cd ../../

      # 3) Fetch signing files and apply to the project
      - |
        echo "🔐 Fetching & applying signing profiles"
        keychain initialize
        app-store-connect fetch-signing-files "com.expressfitness.x45" --type IOS_APP_STORE --create
        cd ios/App
        xcode-project use-profiles
        cd ../../

      # 4) Build signed IPA (workspace + export options)
      - |
        echo "🏗️ Building signed IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination 'generic/platform=iOS'" \
          --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
