workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.expressfitness.x45
      groups:
        - apple-connect  # APP_STORE_CONNECT_* + CERTIFICATE_PRIVATE_KEY

    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor iOS, then write a *minimal* Podfile (no helper, no post_install)
      - |
        set -euo pipefail
        echo "👉 Setting up Capacitor"
        npm i -g @capacitor/cli
        npm i @capacitor/core @capacitor/ios --save --no-fund --no-audit || true

        if [ ! -d ios ]; then
          echo "➕ Adding iOS platform"
          npx cap add ios
        fi

        echo "📝 Writing minimal Podfile"
        # Nuke any previous Podfile that might be half-written
        rm -f ios/App/Podfile

        # Use printf to avoid heredoc/indent pitfalls
        printf "platform :ios, '13.0'\n"                                   >> ios/App/Podfile
        printf "use_frameworks! :linkage => :static\n\n"                   >> ios/App/Podfile
        printf "target 'App' do\n"                                         >> ios/App/Podfile
        printf "  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'\n" >> ios/App/Podfile
        printf "  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'\n" >> ios/App/Podfile
        # Add plugin pods explicitly if you use them (uncomment/extend as needed):
        # printf \"  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'\\n\" >> ios/App/Podfile
        # printf \"  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'\\n\" >> ios/App/Podfile
        printf "end\n"                                                     >> ios/App/Podfile

        echo "🔎 Show Podfile contents:"
        nl -ba ios/App/Podfile

        echo "🔄 Sync native"
        npx cap copy ios
        # Don't let sync run pods—our next step handles pods
        npx cap sync ios || true

      # 2) Clean CocoaPods cache (defensive), then install
      - |
        set -euo pipefail
        echo "🧹 CocoaPods cleanup (defensive)"
        cd ios/App
        rm -f Podfile.lock
        rm -rf Pods
        pod repo update
        echo "📦 Installing CocoaPods"
        pod install --repo-update
        cd ../../
        ls -la ios/App

      # 3) Signing
      - |
        set -euo pipefail
        echo "🔐 Fetching & applying signing profiles"
        keychain initialize
        app-store-connect fetch-signing-files "$BUNDLE_ID" \
          --type IOS_APP_STORE \
          --create \
          --certificate-private-key "$CERTIFICATE_PRIVATE_KEY"
        keychain add-certificates
        xcode-project use-profiles \
          --workspace ios/App/App.xcworkspace \
          --scheme App

      # 4) Build signed IPA (Release)
      - |
        set -euo pipefail
        echo "🏗️ Archiving & exporting IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination generic/platform=iOS"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log
      - ~/Library/Logs/gym/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
