workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
      groups:
        - apple-connect     # <-- pulls ISSUER_ID, KEY_IDENTIFIER, PRIVATE_KEY
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor iOS (recreate if needed)
      - |
        echo "ðŸ‘‰ Setting up Capacitor"
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/ios --save --no-fund --no-audit || true
        npx cap init "X45 Express Fitness" "com.expressfitness.x45" --web-dir=www --npm-client=npm || true
        if [ ! -f ios/App/App.xcodeproj ]; then
          echo "ðŸ§¹ Recreating ios platform"
          rm -rf ios
          npx cap add ios
        fi
        npx cap copy ios
        npx cap sync ios

      # 2) Install CocoaPods (creates the .xcworkspace)
      - |
        echo "ðŸ“¦ Installing CocoaPods"
        cd ios/App
        pod install --repo-update
        cd ../../

      # 3) Fetch signing files and APPLY them to the workspace + scheme
      - |
        echo "ðŸ” Fetching & applying signing profiles"
        keychain initialize
        app-store-connect fetch-signing-files "com.expressfitness.x45" --type IOS_APP_STORE --create
        keychain add-certificates
        xcode-project use-profiles --workspace ios/App/App.xcworkspace --scheme App

      # 4) Build signed IPA (use workspace + export options)
      - |
        echo "ðŸ—ï¸ Building signed IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination 'generic/platform=iOS'" \
          --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
