workflows:
  ios-capacitor:
    name: X45 iOS (Capacitor)
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Prepare Capacitor + pods
      - |
        echo "ðŸ‘‰ Setting up Capacitor"
        npm i -g @capacitor/cli
        npm i @capacitor/core @capacitor/ios --save --no-fund --no-audit || true
        npx cap init "X45 Express Fitness" "com.expressfitness.x45" --web-dir=www || true
        npx cap add ios || true
        npx cap copy ios
        cd ios/App && pod install --repo-update && cd ../../

      # 2) Fix hard-coded Team ID & wrong signing identity in the project
      - |
        echo "ðŸ§½ Fixing team id and signing identities"
        TEAM_ID="Q2F9G3GYF7"   # <-- your real Apple Team ID
        # Force the correct team id everywhere
        sed -i '' "s/DEVELOPMENT_TEAM = [A-Z0-9]\{10\}/DEVELOPMENT_TEAM = ${TEAM_ID}/g" ios/App/App.xcodeproj/project.pbxproj || true
        # Make sure Release signs with Apple Distribution (not iOS Development)
        sed -i '' 's/CODE_SIGN_IDENTITY = "iOS Development"/CODE_SIGN_IDENTITY = "Apple Distribution"/g' ios/App/App.xcodeproj/project.pbxproj || true
        sed -i '' 's/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "iOS Development"/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = "Apple Distribution"/g' ios/App/App.xcodeproj/project.pbxproj || true

      # 3) Download certs/profiles & apply them to the workspace + scheme
      - |
        echo "ðŸ” Downloading and applying signing profiles"
        keychain initialize
        app-store-connect fetch-signing-files "com.expressfitness.x45" --type IOS_APP_STORE --create
        keychain add-certificates
        xcode-project use-profiles --workspace ios/App/App.xcworkspace --scheme App

      # 4) Build the IPA (Release, generic device)
      - |
        echo "ðŸ—ï¸ Building IPA"
        xcode-project build-ipa \
          --workspace ios/App/App.xcworkspace \
          --scheme App \
          --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.log

    publishing:
      email:
        recipients:
          - alexbabinets@gmail.com
        notify:
          success: true
          failure: true
